name: build-i386-linux
run-name: Build Linux binary for i386
on: [push, workflow_dispatch]

jobs:
  clone-and-build-repo:
    runs-on: ubuntu-20.04
    steps:
      - name: Get dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libc6-dev-i386
      - name: Clone an Inferno repository
        run: |
          git clone https://github.com/dboddie/inferno-os.git inferno-os
      - name: Build the host system
        run: |
          cd $GITHUB_WORKSPACE/inferno-os
          sed -ri 's|/usr\/inferno|'$PWD'|' mkconfig
          sed -ri 's/SYSHOST=Plan9/SYSHOST=Linux/' mkconfig
          sed -ri 's/#OBJTYPE/OBJTYPE/' mkconfig
          sed -ri 's/OBJTYPE=\$/#OBJTYPE=\$/' mkconfig
          sed -ri 's/\temu/#\temu/' mkfile
          ./makemk.sh
          export PATH=$PWD/Linux/386/bin/:$PATH
          mk nuke
          mk mkdirs
          mk install
      - name: Clone the packaging repo and copy things into the hosted root
        run: |
          git clone https://gitlab.com/dboddie/limbo-packager.git
          cp limbo-packager/package.sh inferno-os/tmp/
      - name: Check out gridchat
        uses: actions/checkout@v4
        with:
          path: 'gridchat'
      - name: Copy files
        run: |
          cp -r gridchat inferno-os/tmp/
      - name: Create a package
        run: |
          inferno-os/Linux/386/bin/emu /tmp/package.sh /tmp/gridchat/gridchat.pkg /tmp/files
          cp inferno-os/Linux/386/bin/emu tmp/files/
          echo './emu -r . -g600x600 /run' > tmp/files/run.sh
          chmod a+x tmp/files/run.sh
          zip -9r gridchat.zip tmp/files
